CREATE TABLE PRODUCENCI 
(
  ID_PRODUCENTA NUMBER(6) NOT NULL 
, NAZWA VARCHAR2(80) NOT NULL 
, KRAJ_PRODUKCJI VARCHAR2(40) 
, CONSTRAINT PRODUCENCI_PK PRIMARY KEY 
  (
    ID_PRODUCENTA 
  )
  ENABLE 
);

CREATE TABLE RODZAJE_SPRZETU 
(
  ID_RODZAJU NUMBER(6) NOT NULL 
, NAZWA VARCHAR2(40) NOT NULL 
, OPIS VARCHAR2(256) 
, CONSTRAINT RODZAJE_SPRZETU_PK PRIMARY KEY 
  (
    ID_RODZAJU 
  )
  ENABLE 
);

CREATE TABLE PARAMETRY 
(
  ID_PARAMETRU NUMBER(8) NOT NULL 
, NAZWA VARCHAR2(40) NOT NULL 
, TYP_WARTOSCI CHAR(1) NOT NULL 
, JEDNOSTKA VARCHAR2(20) 
, ID_RODZAJU NUMBER(6) NOT NULL 
, CONSTRAINT PARAMETRY_PK PRIMARY KEY 
  (
    ID_PARAMETRU 
  , TYP_WARTOSCI 
  )
  ENABLE 
);

CREATE TABLE SPRZETY 
(
  ID_SPRZETU NUMBER(8) NOT NULL 
, NAZWA_MODELU VARCHAR2(80) NOT NULL 
, CENA NUMBER(8, 2) 
, ILOSC NUMBER(8) 
, ID_PRODUCENTA NUMBER(6) NOT NULL 
, ID_RODZAJU NUMBER(6) NOT NULL 
, CONSTRAINT SPRZETY_PK PRIMARY KEY 
  (
    ID_SPRZETU 
  )
  ENABLE 
);

CREATE TABLE HISTORIA_CEN 
(
  ID_CENY_SPRZETU NUMBER(16) NOT NULL 
, ID_SPRZETU NUMBER(8) NOT NULL 
, CENA NUMBER(8, 2) NOT NULL 
, DATA_ZMIANY DATE DEFAULT SYSDATE NOT NULL 
, CONSTRAINT HISTORIA_CEN_PK PRIMARY KEY 
  (
    ID_CENY_SPRZETU 
  )
  ENABLE 
);

CREATE TABLE PARAMETRY_SPRZETU 
(
  ID_PARAMETRU NUMBER(8) NOT NULL 
, ID_SPRZETU NUMBER(8) NOT NULL 
, TYP_WARTOSCI CHAR(1) NOT NULL 
, WARTOSC_TEKSTOWA VARCHAR2(80) 
, WARTOSC_NUMERYCZNA NUMBER(24, 8) 
, CONSTRAINT PARAMETRY_SPRZETU_PK PRIMARY KEY 
  (
    ID_PARAMETRU 
  , ID_SPRZETU 
  )
  ENABLE 
);

CREATE INDEX HISTORIA_ID_SPRZETU_IDX ON HISTORIA_CEN (ID_SPRZETU ASC);

CREATE INDEX PARAMETRY_ID_RODZAJU_IDX ON PARAMETRY (ID_RODZAJU ASC);

CREATE INDEX PARAMETRY_SPRZETU_IDX ON PARAMETRY_SPRZETU (ID_SPRZETU ASC);

CREATE INDEX SPRZETY_ID_PRODUCENTA_IDX ON SPRZETY (ID_PRODUCENTA ASC);

CREATE INDEX SPRZETY_ID_RODZAJU_IDX ON SPRZETY (ID_RODZAJU ASC);

ALTER TABLE PRODUCENCI
ADD CONSTRAINT PRODUCENCI_UK UNIQUE 
(
  NAZWA 
, KRAJ_PRODUKCJI 
)
ENABLE;

ALTER TABLE RODZAJE_SPRZETU
ADD CONSTRAINT RODZAJE_SPRZETU_UK UNIQUE 
(
  NAZWA 
)
ENABLE;

ALTER TABLE HISTORIA_CEN
ADD CONSTRAINT SPRZETY_HISTORIA_CEN_FK FOREIGN KEY
(
  ID_SPRZETU 
)
REFERENCES SPRZETY
(
  ID_SPRZETU 
)
ENABLE;

ALTER TABLE PARAMETRY
ADD CONSTRAINT RODZAJE_SPRZETU_PARAMETRY_FK FOREIGN KEY
(
  ID_RODZAJU 
)
REFERENCES RODZAJE_SPRZETU
(
  ID_RODZAJU 
)
ENABLE;

ALTER TABLE PARAMETRY_SPRZETU
ADD CONSTRAINT PARAMETRY_PARAM_SPRZETU_FK FOREIGN KEY
(
  ID_PARAMETRU 
, TYP_WARTOSCI 
)
REFERENCES PARAMETRY
(
  ID_PARAMETRU 
, TYP_WARTOSCI 
)
ENABLE;

ALTER TABLE PARAMETRY_SPRZETU
ADD CONSTRAINT SPRZETY_PARAM_SPRZETU_FK FOREIGN KEY
(
  ID_SPRZETU 
)
REFERENCES SPRZETY
(
  ID_SPRZETU 
)
ENABLE;

ALTER TABLE SPRZETY
ADD CONSTRAINT PRODUCENCI_SPRZETY_FK FOREIGN KEY
(
  ID_PRODUCENTA 
)
REFERENCES PRODUCENCI
(
  ID_PRODUCENTA 
)
ENABLE;

ALTER TABLE SPRZETY
ADD CONSTRAINT RODZAJE_SPRZETU_SPRZETY_FK FOREIGN KEY
(
  ID_RODZAJU 
)
REFERENCES RODZAJE_SPRZETU
(
  ID_RODZAJU 
)
ENABLE;

ALTER TABLE PARAMETRY
ADD CONSTRAINT PARAM_TYP_WARTOSCI_CHK CHECK 
(TYP_WARTOSCI IN ( 'T', 'N'))
ENABLE;

ALTER TABLE PARAMETRY_SPRZETU
ADD CONSTRAINT PARAM_SPRZETU_TYP_WARTOSCI_CHK CHECK 
((TYP_WARTOSCI IN ('N') AND WARTOSC_TEKSTOWA IS NULL AND WARTOSC_NUMERYCZNA IS NOT NULL) OR (TYP_WARTOSCI IN ('T') AND WARTOSC_TEKSTOWA IS NOT NULL AND WARTOSC_NUMERYCZNA IS NULL))
ENABLE;

ALTER TABLE SPRZETY
ADD CONSTRAINT CENA_CHK CHECK 
(CENA > 0
)
ENABLE;

ALTER TABLE SPRZETY
ADD CONSTRAINT ILOSC_CHK CHECK 
(ILOSC >= 0)
ENABLE;

COMMENT ON TABLE HISTORIA_CEN IS 'Tabela zawiera historie cen dla tych sprzetow, ktorych cena zostala zmodyfikowana';

COMMENT ON TABLE PARAMETRY_SPRZETU IS 'Wartosc parametru w WARTOSC_TEKSTOWA lub WARTOSC_NUMERYCZNA';

COMMENT ON TABLE PRODUCENCI IS 'Na jednego producenta moze przypadac wiele krajow produkcji.';

COMMENT ON COLUMN HISTORIA_CEN.DATA_ZMIANY IS 'Data, kiedy dana cena przestala byc obowiazujaca';

COMMENT ON COLUMN PARAMETRY.TYP_WARTOSCI IS 'T = wartosc tekstowa, N = wartosc numeryczna';

COMMENT ON COLUMN PARAMETRY.JEDNOSTKA IS 'Null = brak danych';

COMMENT ON COLUMN PRODUCENCI.KRAJ_PRODUKCJI IS 'Null = brak danych';

COMMENT ON COLUMN SPRZETY.CENA IS 'Null = brak danych';

COMMENT ON COLUMN SPRZETY.ILOSC IS 'Null = brak danych';
