INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Karta graficzna');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Procesor');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Płyta główna');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Pamięć RAM');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Obudowa');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Zasilacz');
INSERT INTO RODZAJE_SPRZETU (NAZWA, OPIS)
VALUES ('Dysk HDD','Pamięć masowa wykorzystująca nośnik magnetyczny do przechowywania danych');
INSERT INTO RODZAJE_SPRZETU (NAZWA, OPIS)
VALUES ('Dysk SSD','Urządzenie pamięci masowej zbudowane w oparciu o pamięć flash');
INSERT INTO RODZAJE_SPRZETU (NAZWA, OPIS)
VALUES ('Pendrive', 'Urządzenie przenośne zawierające pamięć nieulotną typu flash, zaprojektowane do współpracy z komputerem przez port USB i używane do przenoszenia danych między komputerami oraz urządzeniami obsługującymi pamięci USB');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Dysk zewnętrzny');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Kieszeń na dysk');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Karta pamięci');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Czytnik kart pamięci');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Płyta CD');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Płyta DVD');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Laptop');
INSERT INTO RODZAJE_SPRZETU (NAZWA)
VALUES ('Ultrabook');

INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Asus', 'Republika Chińska');
INSERT INTO PRODUCENCI (NAZWA) VALUES ('Asus');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Gigabyte', 'Republika Chińska');
INSERT INTO PRODUCENCI (NAZWA) VALUES ('Gigabyte');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('MSI', 'Republika Chińska');
INSERT INTO PRODUCENCI (NAZWA) VALUES ('MSI');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Hewlett-Packard Company', 'Stany Zjednoczone');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Hewlett-Packard Company', 'Irlandia');
INSERT INTO PRODUCENCI (NAZWA) VALUES ('Hewlett-Packard Company');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Intel', 'Stany Zjednoczone');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Intel', 'Irlandia');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Intel', 'Izrael');
INSERT INTO PRODUCENCI (NAZWA) VALUES ('Intel');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Advanced Micro Devices, Inc.', 'Stany Zjednoczone');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Advanced Micro Devices, Inc.', 'Niemcy');
INSERT INTO PRODUCENCI (NAZWA) VALUES ('Advanced Micro Devices, Inc.');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('ADATA Technology Co.', 'Republika Chińska');
INSERT INTO PRODUCENCI (NAZWA) VALUES ('ADATA Technology Co.');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Seagate Technology', 'Stany Zjednoczone');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('Seagate Technology', 'Republika Chińska');
INSERT INTO PRODUCENCI (NAZWA) VALUES ('Seagate Technology');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('SanDisk Corporation', 'Stany Zjednoczone');
INSERT INTO PRODUCENCI (NAZWA, KRAJ_PRODUKCJI) VALUES ('SanDisk Corporation', 'Japonia');
INSERT INTO PRODUCENCI (NAZWA) VALUES ('SanDisk Corporation');

INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('GeForce GTX 1050 TI', 839.00, 50, 1, 1);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('GeForce GTX 1070', 2187.00, 8, 1, 1);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('GeForce GTX 1060', 995.00, 14, 2, 1);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('Core i5-7400', 709.00, 40, 7, 2);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('Core i3-7100', 464.99, 35, 8, 2);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('Ryzen 5 1600', 860, 20, 10, 2);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('SU800', 235, 30, 12, 8);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('SU900', 440, 20, 13, 8);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('HC660', 223.89, 2, 12, 9);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('SDXC 64GB Class 10', 104.86, 12, 13, 11);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('B250M PRO-VDH', 285, 21, 3, 3);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('Z370 AORUS Gaming K3', 579, 14, 2, 3);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('B85M-G', 315, 8, 1, 3);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('Backup Plus, 2TB', 339.89, 4, 31, 9);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('Expansion, 2TB', 324.99, 6, 31, 9);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('Ultra SDHC 64GB', 98.95, 5, 34, 11);
INSERT INTO SPRZETY (NAZWA_MODELU, CENA, ILOSC, ID_PRODUCENTA, ID_RODZAJU)
VALUES ('Extreme PRO SDXC 128 GB', 321, 4, 35, 11);

INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Producent chipsetu', 'T', '', 1);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Rodzaj chipsetu', 'T', '', 1);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Ilość pamięci RAM', 'N', 'GB', 1);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Rodzaj pamięci RAM', 'T', '', 1);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Typ złącza', 'T', '', 1);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Taktowanie rdzenia', 'N', 'MHz', 1);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Taktowanie pamięci', 'N', 'MHz', 1);

INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Linia', 'T', '', 2);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Typ gniazda', 'T', '', 2);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Liczba rdzeni', 'N', '', 2);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Liczba wątków', 'N', '', 2);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Częstotliwość taktowania procesora', 'N', 'GHz', 2);

INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Standard płyty', 'T', '', 3);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Chipset płyty', 'T', '', 3);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Gniazdo procesora', 'T', '', 3);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Maksymalna ilość procesorów', 'N', '', 3);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Standard pamięci', 'T', '', 3);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Ilość slotów pamięci', 'N', '', 3);
INSERT INTO PARAMETRY (NAZWA, TYP_WARTOSCI, JEDNOSTKA, ID_RODZAJU)
VALUES ('Maksymalna ilość pamięci', 'N', 'GB', 3);

INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 8, 1, TYP_WARTOSCI, 'NVIDIA', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 8;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 9, 1, TYP_WARTOSCI, 'GeForce GTX 1050 Ti', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 9;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 10, 1, TYP_WARTOSCI, NULL, 4 FROM PARAMETRY WHERE ID_PARAMETRU = 10;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 11, 1, TYP_WARTOSCI, 'GDDR5', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 11;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 12, 1, TYP_WARTOSCI, 'PCI Express x16', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 12;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 13, 1, TYP_WARTOSCI, NULL, 1392 FROM PARAMETRY WHERE ID_PARAMETRU = 13;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 14, 1, TYP_WARTOSCI, NULL, 7008 FROM PARAMETRY WHERE ID_PARAMETRU = 14;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 8, 4, TYP_WARTOSCI, 'NVIDIA', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 8;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 9, 4, TYP_WARTOSCI, 'GeForce GTX 1070', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 9;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 10, 4, TYP_WARTOSCI, NULL, 8 FROM PARAMETRY WHERE ID_PARAMETRU = 10;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 11, 4, TYP_WARTOSCI, 'GDDR5', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 11;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 12, 4, TYP_WARTOSCI, 'PCI Express x16', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 12;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 13, 4, TYP_WARTOSCI, NULL, 1657 FROM PARAMETRY WHERE ID_PARAMETRU = 13;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 14, 4, TYP_WARTOSCI, NULL, 8000 FROM PARAMETRY WHERE ID_PARAMETRU = 14;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 8, 5, TYP_WARTOSCI, 'NVIDIA', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 8;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 9, 5, TYP_WARTOSCI, 'GeForce GTX 1060', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 9;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 10, 5, TYP_WARTOSCI, NULL, 3 FROM PARAMETRY WHERE ID_PARAMETRU = 10;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 11, 5, TYP_WARTOSCI, 'GDDR5', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 11;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 12, 5, TYP_WARTOSCI, 'PCI Express x16', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 12;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 13, 5, TYP_WARTOSCI, NULL, 1582 FROM PARAMETRY WHERE ID_PARAMETRU = 13;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 14, 5, TYP_WARTOSCI, NULL, 8008 FROM PARAMETRY WHERE ID_PARAMETRU = 14;

INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 15, 6, TYP_WARTOSCI, 'Core i5', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 15;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 16, 6, TYP_WARTOSCI, 'Socket 1151', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 16;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 17, 6, TYP_WARTOSCI, NULL, 4 FROM PARAMETRY WHERE ID_PARAMETRU = 17;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 18, 6, TYP_WARTOSCI, NULL, 4 FROM PARAMETRY WHERE ID_PARAMETRU = 18;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 19, 6, TYP_WARTOSCI, NULL, 3 FROM PARAMETRY WHERE ID_PARAMETRU = 19;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 15, 7, TYP_WARTOSCI, 'Core i3', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 15;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 16, 7, TYP_WARTOSCI, 'Socket 1151', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 16;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 17, 7, TYP_WARTOSCI, NULL, 2 FROM PARAMETRY WHERE ID_PARAMETRU = 17;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 18, 7, TYP_WARTOSCI, NULL, 4 FROM PARAMETRY WHERE ID_PARAMETRU = 18;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 19, 7, TYP_WARTOSCI, NULL, 3.9 FROM PARAMETRY WHERE ID_PARAMETRU = 19;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 15, 8, TYP_WARTOSCI, 'Ryzen 5', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 15;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 16, 8, TYP_WARTOSCI, 'Socket AM4', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 16;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 17, 8, TYP_WARTOSCI, NULL, 6 FROM PARAMETRY WHERE ID_PARAMETRU = 17;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 18, 8, TYP_WARTOSCI, NULL, 12 FROM PARAMETRY WHERE ID_PARAMETRU = 18;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 19, 8, TYP_WARTOSCI, NULL, 3.2 FROM PARAMETRY WHERE ID_PARAMETRU = 19;

INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 20, 20, TYP_WARTOSCI, 'Micro ATX', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 20;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 21, 20, TYP_WARTOSCI, 'Intel B250', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 21;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 22, 20, TYP_WARTOSCI, 'Socket 1151', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 22;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 23, 20, TYP_WARTOSCI, NULL, 1 FROM PARAMETRY WHERE ID_PARAMETRU = 23;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 24, 20, TYP_WARTOSCI, 'DDR4' ,NULL FROM PARAMETRY WHERE ID_PARAMETRU = 24;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 25, 20, TYP_WARTOSCI, NULL, 4 FROM PARAMETRY WHERE ID_PARAMETRU = 25;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 26, 20, TYP_WARTOSCI, NULL, 64 FROM PARAMETRY WHERE ID_PARAMETRU = 26;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 20, 21, TYP_WARTOSCI, 'ATX', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 20;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 21, 21, TYP_WARTOSCI, 'Intel Z370', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 21;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 22, 21, TYP_WARTOSCI, 'Socket 1151 (Coffee Lake)', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 22;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 23, 21, TYP_WARTOSCI, NULL, 1 FROM PARAMETRY WHERE ID_PARAMETRU = 23;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 24, 21, TYP_WARTOSCI, 'DDR4' ,NULL FROM PARAMETRY WHERE ID_PARAMETRU = 24;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 25, 21, TYP_WARTOSCI, NULL, 4 FROM PARAMETRY WHERE ID_PARAMETRU = 25;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 26, 21, TYP_WARTOSCI, NULL, 64 FROM PARAMETRY WHERE ID_PARAMETRU = 26;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 20, 22, TYP_WARTOSCI, 'Micro ATX', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 20;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 21, 22, TYP_WARTOSCI, 'Intel B85', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 21;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 22, 22, TYP_WARTOSCI, 'Socket 1150', NULL FROM PARAMETRY WHERE ID_PARAMETRU = 22;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 23, 22, TYP_WARTOSCI, NULL, 1 FROM PARAMETRY WHERE ID_PARAMETRU = 23;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 24, 22, TYP_WARTOSCI, 'DDR3' ,NULL FROM PARAMETRY WHERE ID_PARAMETRU = 24;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 25, 22, TYP_WARTOSCI, NULL, 4 FROM PARAMETRY WHERE ID_PARAMETRU = 25;
INSERT INTO PARAMETRY_SPRZETU (ID_PARAMETRU, ID_SPRZETU, TYP_WARTOSCI, WARTOSC_TEKSTOWA, WARTOSC_NUMERYCZNA)
SELECT 26, 22, TYP_WARTOSCI, NULL, 32 FROM PARAMETRY WHERE ID_PARAMETRU = 26;
