CREATE SEQUENCE ID_CENY_SPRZETU_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_PARAMETRU_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_SPRZETU_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_PRODUCENTA_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_RODZAJU_SEQ START WITH 1 INCREMENT BY 1;

-- TRIGGERS FOR SEQUENCES

CREATE OR REPLACE TRIGGER ID_CENY_SPRZETU_AUTOINC 
    BEFORE INSERT ON HISTORIA_CEN 
    FOR EACH ROW
WHEN( NEW.ID_CENY_SPRZETU IS NULL )
BEGIN
    :NEW.ID_CENY_SPRZETU := ID_CENY_SPRZETU_SEQ.NEXTVAL;
END; 

CREATE OR REPLACE TRIGGER ID_PARAMETRU_AUTOINC 
    BEFORE INSERT ON PARAMETRY
    FOR EACH ROW
WHEN( NEW.ID_PARAMETRU IS NULL )
BEGIN
    :NEW.ID_PARAMETRU := ID_PARAMETRU_SEQ.NEXTVAL;
END; 

CREATE OR REPLACE TRIGGER ID_SPRZETU_AUTOINC 
    BEFORE INSERT ON SPRZETY
    FOR EACH ROW
WHEN( NEW.ID_SPRZETU IS NULL )
BEGIN
    :NEW.ID_SPRZETU := ID_SPRZETU_SEQ.NEXTVAL;
END; 

CREATE OR REPLACE TRIGGER ID_PRODUCENTA_AUTOINC 
    BEFORE INSERT ON PRODUCENCI
    FOR EACH ROW
WHEN( NEW.ID_PRODUCENTA IS NULL )
BEGIN
    :NEW.ID_PRODUCENTA := ID_PRODUCENTA_SEQ.NEXTVAL;
END; 

CREATE OR REPLACE TRIGGER ID_RODZAJU_AUTOINC 
    BEFORE INSERT ON RODZAJE
    FOR EACH ROW 
WHEN( NEW.ID_RODZAJU IS NULL )
BEGIN
    :NEW.ID_RODZAJU := ID_RODZAJU_SEQ.NEXTVAL;
END; 