CREATE OR REPLACE TRIGGER ZAPISZ_CENE
AFTER INSERT OR UPDATE OF CENA ON SPRZETY
FOR EACH ROW
WHEN( NEW.CENA IS NOT NULL )
BEGIN
    INSERT INTO HISTORIA_CEN ( ID_SPRZETU, CENA ) VALUES ( :NEW.ID_SPRZETU, :NEW.CENA);
END;
